filter_type = dict(GLOBAL = ("GLOBAL_Avg",1.2,1.2,50),
                   DIFFUSE = ("DIFFUSE_Avg",0.95,1.2,10),
                   DIRECT = ("DIRECT_Avg",0.95,0.2,10))

options_type = {"Parametros Basicos"    : (option:=1, 
                                           rows:=1, 
                                           cols:=1, 
                                           label_xaxe := ["Dia, Hora"],
                                           label_yaxe := ["W/m^2"] ),
                "Balance de onda corta" : (option:=2, 
                                           rows:=1, 
                                           cols:=1, 
                                           label_xaxe := ["Dia, Hora"],
                                           label_yaxe := ["W/m^2"]),
                "Balance de onda larga" : (option:=3, 
                                           rows:=2, 
                                           cols:=1, 
                                           label_xaxe := ["Dia, Hora"]*2,
                                           label_yaxe := ["W/m^2","Temp (K)"]),
                "Meteorologia"          : (option:=4, 
                                           rows:=2, 
                                           cols:=2, 
                                           label_xaxe := ["Dia, Hora"]*4,
                                           label_yaxe := ["Temp (K)","mbar","%","Temp (K)"]),
                "Ultravioleta"          : (option:=5, 
                                           rows:=3, 
                                           cols:=1, 
                                           label_xaxe := ["Dia, Hora"]*3,
                                           label_yaxe := ["UVB","Temp (K)","UVB"]),
                "Dispersion"            : (option:=6, 
                                           rows:=3, 
                                           cols:=1, 
                                           label_xaxe := ["Dia, Hora","Dia, Hora","W/m^2"],
                                           label_yaxe := ["W/m^2"," ","W/m^2"]),
                "Otros"                 : (option:=7, 
                                           rows:=1, 
                                           cols:=1, 
                                           label_xaxe := [" "],
                                           label_yaxe := [" "])
               }
